# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ec5ffd07b0526230625af25cf2c287ae9ddfb5ddb8a17edd55e4f44495726ed1bbc8ffcdd952b2d2f626ab2e207b0e2ea3cc8a9ef4651276df69b05c8def913f

test:
  secret_key_base: d47ab289d5327986fb04b8f7b143858eb34eadca169f3fc2ef07b66bae2e177d39093cb9fe6c1ae24f3e2b2d895b14d2fd182c7f5fa93875ec0bb9cfaba1a691

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
